version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru
    networks:
      - pothole-net

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000" 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    env_file:
      - .env
    volumes:
      - ./yolov11_weight/best_remya.pt:/app/yolov11_weight/best_remya.pt
    networks:
      - pothole-net

  celery:
    build: .
    container_name: celery
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=1
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    env_file:
      - .env
    volumes:
      - ./yolov11_weight/best_remya.pt:/app/yolov11_weight/best_remya.pt
    networks:
      - pothole-net

networks:
  pothole-net:
    driver: bridge



